// ── fournisseurs.js v6 ────────────────────────────────────

async function loadFournisseurs() {
  try {
    const fournisseurs = await api('/api/fournisseurs') || [];

    // Auto-code preview
    const codes = fournisseurs.filter(f=>(f.code||'').startsWith('FOURN-')).sort((a,b)=>b.code.localeCompare(a.code));
    const nextN = codes.length ? parseInt(codes[0].code.split('-')[1]||0)+1 : 1;
    if ($('fourn-code-preview')) $('fourn-code-preview').textContent = `FOURN-${String(nextN).padStart(3,'0')}`;

    const sMap  = { ACTIF:'b-completed', INACTIF:'b-draft', BLACKLISTE:'b-urgent' };
    const sIcon = { ACTIF:'✓', INACTIF:'○', BLACKLISTE:'✕' };

    $('fournisseurs-table').innerHTML = fournisseurs.length === 0 ? empty(8, 'Aucun fournisseur') :
      `<table><thead><tr>
        <th>Code</th><th>Raison Sociale</th><th>Contact</th>
        <th>Téléphone</th><th>Email</th><th>Ville</th><th>Statut</th><th>Actions</th>
      </tr></thead><tbody>
      ${fournisseurs.map(f => `<tr>
        <td><span class="of-num" style="font-size:9px">${f.code||'—'}</span></td>
        <td>
          <strong>${f.nom}</strong>
          ${f.matricule_fiscal?`<div style="font-size:9px;font-family:'IBM Plex Mono',monospace;color:var(--muted)">MF: ${f.matricule_fiscal}</div>`:''}
        </td>
        <td style="font-size:11px">${f.contact||'—'}</td>
        <td style="font-family:'IBM Plex Mono',monospace;font-size:10px">${f.telephone||'—'}</td>
        <td style="font-size:11px;color:var(--muted)">${f.email||'—'}</td>
        <td style="font-size:11px">${[f.ville,f.pays].filter(Boolean).join(', ')||'—'}</td>
        <td><span class="badge ${sMap[f.statut]||'b-draft'}">${sIcon[f.statut]||''} ${f.statut}</span></td>
        <td style="display:flex;gap:3px">
          <button class="fbtn" onclick="openEditFournisseur(${f.id})" title="Modifier">✎</button>
          <select class="fbtn" onchange="updateFournisseurStatut(${f.id},this.value);this.value=''"
            style="font-size:9px;padding:2px 4px;background:var(--bg3);border:1px solid var(--border);border-radius:4px;color:var(--text)">
            <option value="">Statut ▾</option>
            <option value="ACTIF">✓ Actif</option>
            <option value="INACTIF">○ Inactif</option>
            <option value="BLACKLISTE">✕ Blacklisté</option>
          </select>
        </td>
      </tr>`).join('')}
      </tbody></table>`;

  } catch(e) { toast('Erreur fournisseurs: ' + e.message, 'err'); }
}

async function saveFournisseur() {
  if (!$('f-nom')?.value?.trim()) { toast('Nom obligatoire', 'err'); return; }
  try {
    await api('/api/fournisseurs', 'POST', {
      nom:               $('f-nom').value.trim(),
      code:              null,  // auto-generated by backend
      contact:           $('f-contact')?.value.trim() || null,
      telephone:         $('f-tel')?.value.trim()     || null,
      email:             $('f-email')?.value.trim()   || null,
      ville:             $('f-ville')?.value.trim()   || null,
      pays:              $('f-pays')?.value.trim()    || 'Tunisie',
      matricule_fiscal:  $('f-mf')?.value.trim()      || null,
      adresse:           $('f-adresse')?.value.trim() || null
    });
    toast('Fournisseur créé ✓'); closeModal('modal-fournisseur'); loadFournisseurs();
  } catch(e) { toast(e.message, 'err'); }
}

function openEditFournisseur(id) {
  api(`/api/fournisseurs/${id}`).then(f => {
    if (!f) return;
    $('f-nom').value     = f.nom        || '';
    $('f-contact').value = f.contact    || '';
    $('f-tel').value     = f.telephone  || '';
    $('f-email').value   = f.email      || '';
    $('f-ville').value   = f.ville      || 'Sfax';
    $('f-pays').value    = f.pays       || 'Tunisie';
    $('f-mf').value      = f.matricule_fiscal || '';
    $('f-adresse').value = f.adresse    || '';
    if ($('fourn-code-preview')) $('fourn-code-preview').textContent = f.code || '—';
    // Store edit id
    window._editFournId = id;
    document.querySelector('#modal-fournisseur .modal-title').textContent = `MODIFIER — ${f.nom}`;
    document.querySelector('#modal-fournisseur .modal-f .btn:last-child').textContent = '💾 Enregistrer';
    document.querySelector('#modal-fournisseur .modal-f .btn:last-child').onclick = saveEditFournisseur;
    openModal('modal-fournisseur');
  });
}

async function saveEditFournisseur() {
  const id = window._editFournId;
  if (!id) return;
  try {
    await api(`/api/fournisseurs/${id}`, 'PUT', {
      nom:              $('f-nom')?.value.trim()     || null,
      contact:          $('f-contact')?.value.trim() || null,
      telephone:        $('f-tel')?.value.trim()     || null,
      email:            $('f-email')?.value.trim()   || null,
      ville:            $('f-ville')?.value.trim()   || null,
      pays:             $('f-pays')?.value.trim()    || null,
      matricule_fiscal: $('f-mf')?.value.trim()      || null,
      adresse:          $('f-adresse')?.value.trim() || null
    });
    toast('Fournisseur mis à jour ✓');
    closeModal('modal-fournisseur');
    window._editFournId = null;
    // Reset modal to create mode
    document.querySelector('#modal-fournisseur .modal-title').textContent = 'NOUVEAU FOURNISSEUR';
    const btn = document.querySelector('#modal-fournisseur .modal-f .btn:last-child');
    btn.textContent = 'Enregistrer'; btn.onclick = saveFournisseur;
    loadFournisseurs();
  } catch(e) { toast(e.message, 'err'); }
}

async function updateFournisseurStatut(id, statut) {
  if (!statut) return;
  try {
    await api(`/api/fournisseurs/${id}`, 'PUT', { statut });
    toast(`Statut → ${statut} ✓`); loadFournisseurs();
  } catch(e) { toast(e.message, 'err'); }
}